/**
 * Computed Timeline Types
 *
 * Types for the timeline computed from V3 scripts after TTS generation.
 * Contains absolute times derived from real audio durations.
 */

import type { AudioTrackType, SegmentContent } from './script.types';

/**
 * Computed segment with absolute positioning
 *
 * Created by TimelineComputationService after TTS generation
 * provides real audio durations.
 */
export interface ComputedSegment {
  /** Unique segment identifier (matches script segment id) */
  id: string;
  /** Track this segment belongs to */
  trackId: string;
  /** Absolute start time in seconds (computed from real durations) */
  startTime: number;
  /** Actual duration in seconds (from TTS/asset metadata) */
  duration: number;
  /** Computed end time (startTime + duration) */
  endTime: number;
  /** Reference to the audio asset in storage */
  audioAssetId?: string;
  /** Direct URL to audio (for convenience) */
  audioUrl?: string;
  /** Original segment content */
  content: SegmentContent;
}

/**
 * Computed track with segments
 */
export interface ComputedTrack {
  /** Unique track identifier */
  id: string;
  /** Track type */
  type: AudioTrackType;
  /** Human-readable track name */
  name: string;
  /** Computed segments with absolute times */
  segments: ComputedSegment[];
}

/**
 * Computed timeline metadata
 */
export interface ComputedTimelineMetadata {
  /** Total duration in seconds (end of last segment) */
  totalDuration: number;
  /** When the timeline was computed */
  computedAt: string;
  /** Pause between voice segments in seconds */
  voiceSegmentPauseSeconds: number;
  /** Number of voice segments */
  voiceSegmentCount: number;
  /** Number of non-voice segments */
  nonVoiceSegmentCount: number;
}

/**
 * Computed Timeline
 *
 * The final timeline with absolute times, ready for FFmpeg mixing.
 * Generated by TimelineComputationService from:
 * 1. V3 Script (relative timing hints)
 * 2. Generated audio assets (real durations)
 *
 * Stored in the computed_timelines table for:
 * - FFmpeg mixing input
 * - Admin UI visualization
 * - Story playback coordination
 */
export interface ComputedTimeline {
  /** Story ID this timeline belongs to */
  storyId: string;
  /** Timeline metadata */
  metadata: ComputedTimelineMetadata;
  /** Computed tracks with absolute times */
  tracks: ComputedTrack[];
}

/**
 * Audio asset with duration for timeline computation
 */
export interface AudioAssetWithDuration {
  /** Asset ID (matches segment id in script) */
  id: string;
  /** Segment ID this asset corresponds to */
  segmentId: string;
  /** Audio duration in seconds (from TTS/storage) */
  durationSeconds: number;
  /** Storage URL/path */
  url: string;
}

/**
 * Input for timeline computation
 */
export interface ComputeTimelineInput {
  /** Story ID */
  storyId: string;
  /** V3 Script with relative timing */
  scriptVersion: 3;
  /** Voice assets with real durations */
  voiceAssets: AudioAssetWithDuration[];
  /** SFX assets with real durations */
  sfxAssets?: AudioAssetWithDuration[];
  /** Music assets with durations */
  musicAssets?: AudioAssetWithDuration[];
  /** Ambiance assets with durations */
  ambianceAssets?: AudioAssetWithDuration[];
  /** Override pause between voice segments (defaults to script metadata) */
  voiceSegmentPauseSeconds?: number;
}
